### ISSUE TITLE
Updates to start,end is not reflecting on slider

### ISSUE THREAD

**Issue by Sunil6591** [webthusiast/time-range-slider#3]
Description - 
To see the updates on slider, we need to update both, the 'value' attribute and 'value' property of start and end of inputs. Ideally updating the 'value' attribute should reflect the changes on slider.

Steps to reproduce
1. Move the slider by dragging, so that the start and end value gets changed.
2. Then externally, try to update the start and end value by setting the 'value' attribute.

**Comment by webthusiast** [comment]
Until `Object.observe` is widely (enough) available, we'll have to use `slider.startValue = ...`.
